language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER testuser WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: dsP3Q6uDdhTRehvxTjMK9l2CbeAhb6zIJHgf3GW0EdzaJJxMGM8DDIG4lCQYYJ+QM95GdxrSNvVctEtiT0d1QRvmh+StqVlxQglMwbXeb+3f+0g07qXwq3MLXH3oGFFTjbDeB7NmJwy9ZETG+gXC6xnNTEYcK0IzQcMeUK5Gv5aB8pWFkpJpvyfge/wjXSFS36Y2merFC9zlo2n0oXdz+y9WbC400MpAZsodyGm/D3At7mGSWP7i/le7jhCt/rykmGdN0AoONFR/808LTS9n3m2vqN9E82knEab1d4yJn9hxCXty2dzO5raB5KAOp/siPHOaatYfj5d9ugbskv4uDEN/yEz1375XapBidMOMrtGjogLIeIZvbRX6PmJm/tdd7SH0H9SKBsUh6ReDoat+UYdtgkgqmWS8uMtKXM5d6RWMX8lLHmfRo5FwS2+4laO4ASS9K7B63WcAF5s75o/roBxAsiZF2mivhZKdYd/aWEg6AGvk12Hp8b1jGfcbAyvimZrp7XN1biI7ugZAzdTYkY2SlptvTmSa3FsmXZ2wJBEcxrYqtqJypXR7QXdM56UCvQm57JHuibjqDRVtjAWrMnlZ+ATSr+BJHQ8t6/HBfyA+J8oR20i98PXnHk2v6C/urq7O7S1tUKKIhl/TKKmE25B5qjz73VOtzYrbQIUQhbk=
  app: ally-invoicify
  on:
    repo: adam-tyler/invoicify-1
