language: java
services:
- postgresql
before_script:
- psql -c 'create database invoicify;' -U postgres
- psql -c "CREATE USER testuser WITH PASSWORD 'admin';" -U postgres
deploy:
  provider: heroku
  api_key:
    secure: TcCX6JQiM4sDkL0cDPEAPQiCjGkugiBmETMWv/CVoq5S7HxoRgAXmyblDXoj3yiCdKBxipsR4ZQi6JXX5qlNbfqIu/9/AjZ0f4zucHDBCDqMF04qUIVdPTd3D+1WLl9MAKHwe30BdwRVrvNhHDmgJM6yEjgtQVFm5M1lyPa7VjJZYUz65mE49VeUOn79ACgkOGermMnlpgDtyBVjQZO5TfE4cgSkqYiIyOXKkEqwCKxe0jlgeXUjKlAcUisJPfs0/w5heOJj8ERajUWPvlbUs7VE3ftBepJjA+HT440YYhfnDJjvZGktTYUe8xE4/rnR+0E5E6xIhWS4qrXKDP3sMysHFyPYAgcWcDx6hAQX3C8rXwTRMZxRVDkzsCtWmJz4kFYu+i/CmAGMm8OYrXsonY6frYsg45ekUNxAa1TJox3H3wjZudBL8YINrR2p4pafm7X7NBksS85UIv/8IamSqtUCrfjCnxtQGDpX74PvqSB41GJ20n7twCFPjTVFkjPM6KtNhWNZI5z94b4aOgB/f6Icl7YuXCfutV0QsboXc8iXaCPvqrdm82S+J11wHjPUELvaa7Gki2Iv3lrnKJCgbzpSKdu84dmZ3gfzNQyAr1/2CGNr1ooNwSrwievJCGyPQOHoCtsHD683N/r2VgnAbJMUQZNpioc51HwfkcE7zP4=
  app: ally-invoicify
  on:
    repo: adam-tyler/invoicify-1
